# Generated by Django 2.0.6 on 2019-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_myuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='advance', max_length=50),
            preserve_default=False,
        ),
    ]
